version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: ffaker
    versions:
    - 2.17.0
