require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-md

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - rubyhub.gemspec

Style/HashSyntax:
  Exclude:
    - spec/rubyhub/operations/pull_request/create_spec.rb
    - spec/rubyhub/configuration_spec.rb

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ExampleLength:
  Enabled: false
