version: 2.1

executors:
  default:
    working_directory: ~/rubyhub
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
      - image: circleci/postgres:10.10
        environment:
          POSTGRES_USER: circleci

commands:
  defaults:
    steps:
      - checkout

      - save_cache:
          paths:
            - /vendor/bundle
          key: v1-dependencies-{{ checksum "rubyhub.gemspec" }}

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "rubyhub.gemspec" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Install Code Climate Test Reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter

  run_linters:
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Fasterer
          command: bundle exec fasterer

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            bundle exec rspec --format documentation \
                              --format RspecJunitFormatter \
                              --out tmp/test-results/rspec/results.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - run:
          name: Code Climate Test Coverage
          command: |
            ./tmp/cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"

      - persist_to_workspace:
        root: coverage
        paths:
          - codeclimate.*.json

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

    upload-coverage:
      environment:
        CC_TEST_REPORTER_ID: e8ca212e976015d9bf1c9a519376032b4919c7da46a7cc30fd14de2eff2a5945
      steps:
        - run:
            command: |
              ./tmp/cc-test-reporter sum-coverage --output - codeclimate.*.json | ./tmp/cc-test-reporter upload-coverage --debug --input -

jobs:
  build_and_test:
    executor: default
    steps:
      - defaults
      - run_linters
  uploading_coverage:
    executor: default
    steps:
      - upload-coverage

workflows:
  version: 2.1
  build:
    jobs:
      - build_and_test
      - uploading_coverage:
        requires:
          - build_and_test
