version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "rubyhub.gemspec" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

  test:
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Fasterer
          command: bundle exec fasterer

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            circleci tests glob "spec/**/*_spec.rb" > test_files.txt
            cat test_files.txt | circleci tests split --split-by=timings > split_test_files.txt

            TESTFILES="$(cat split_test_files.txt | xargs)"
            if [ -z "$TESTFILES" ]; then echo  'No tests are scheduled to be executed on this node'; exit 0; fi

            export SPEC="$TESTFILES"
            export SPEC_OPTS="--format documentation --format RspecJunitFormatter --out tmp/test-results/rspec-${CIRCLE_NODE_INDEX:-0}.xml"

            bundle exec rspec

      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"

      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.*.json

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  upload-coverage:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    environment:
      CC_TEST_REPORTER_ID: e8ca212e976015d9bf1c9a519376032b4919c7da46a7cc30fd14de2eff2a5945
    steps:
      - run:
          command: |
            ./cc-test-reporter sum-coverage --output - codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
            - test
