version: 2.1

executors:
  default:
    parameters:
      tag:
        description: The circleci/ruby Docker image version tag
        type: string
        default: latest
    working_directory: ~/rubyhub
    docker:
      - image: circleci/ruby:<< parameters.tag >>-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
      - image: circleci/postgres:10.10
        environment:
          POSTGRES_USER: circleci

commands:
  cc-setup-coverage:
    description: Setup Code Climate
    parameters:
      url:
        description: Pre-built binary URL
        default: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        type: string
      version:
        default: latest
        type: string
    steps:
      - restore_cache:
          key: cc-setup-<< parameters.version >>
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: cc-setup-<< parameters.version >>
          paths:
            - ./cc-test-reporter

  run_linters:
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Fasterer
          command: bundle exec fasterer

  run_specs:
    steps:
      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            ./cc-test-reporter before-build
            bundle exec rspec --format documentation \
                              --format RspecJunitFormatter \
                              --out tmp/test-results/results.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

  cc-format-coverage:
    steps:
      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.*.json

  cc-upload-coverage:
    description: Upload coverage payload to Code Climate
    steps:
      - run:
          name: Code Climate Upload Coverage
          command: |
            ./cc-test-reporter sum-coverage --output - coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  bundle-load-cache:
    description: Load cached RubyGems
    parameters:
      key:
        description: The cache key to use
        type: string
        default: bundle-v1
    steps:
      - restore_cache:
          key: 'bundle-v1-<< parameters.key >>-{{ arch }}-{{ checksum "rubyhub.gemspec" }}'

  bundle-install:
    description: Install gems with Bundler
    steps:
      - run: bundle install

  bundle-save-cache:
    description: Save RubyGems to cache
    parameters:
      key:
        description: The cache key to use
        type: string
        default: bundle-v1
    steps:
      - save_cache:
          key: 'bundle-v1-<< parameters.key >>-{{ arch }}-{{ checksum "rubyhub.gemspec" }}'
          paths:
            - vendor/bundle
jobs:
  checkout:
    executor: default
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - checkout
      - save_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
      - cc-setup-coverage

  ruby-2-4:
    executor:
      name: default
      tag: "2.4"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - bundle-load-cache:
          key: ruby-2.4
      - bundle-install
      - bundle-save-cache:
          key: ruby-2.4
      - run_linters
      - run_specs
      - cc-format-coverage

  ruby-2-5:
    executor:
      name: default
      tag: "2.5"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - bundle-load-cache:
          key: ruby-2.5
      - bundle-install
      - bundle-save-cache:
          key: ruby-2.5
      - run_linters
      - run_specs
      - cc-format-coverage

  ruby-2-6:
    executor:
      name: default
      tag: "2.6"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - bundle-load-cache:
          key: ruby-2.6
      - bundle-install
      - bundle-save-cache:
          key: ruby-2.6
      - run_linters
      - run_specs
      - cc-format-coverage

  ruby-2-7:
    executor:
      name: default
      tag: "2.7"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - bundle-load-cache:
          key: ruby-2.7
      - bundle-install
      - bundle-save-cache:
          key: ruby-2.7
      - run_linters
      - run_specs
      - cc-format-coverage

  ruby-head:
    executor: default
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - bundle-load-cache:
          key: ruby-head
      - bundle-install
      - bundle-save-cache:
          key: ruby-head
      - run_linters
      - run_specs
      - cc-format-coverage

  cc-upload-coverage:
    executor: default
    steps:
      - cc-upload-coverage

workflows:
  version: 2.1
  build:
    jobs:
      - checkout
      - ruby-2-4:
          requires:
            - checkout
      - ruby-2-5:
          requires:
            - checkout
      - ruby-2-6:
          requires:
            - checkout
      - ruby-2-7:
          requires:
            - checkout
      - ruby-head:
          requires:
            - checkout
      - cc-upload-coverage:
          requires:
            - ruby-2-4
            - ruby-2-5
            - ruby-2-6
            - ruby-2-7
